### ISSUE TITLE
Only one cookie can be set in the response. 

### ISSUE THREAD

**Issue by ghsbhatia** [getsandbox/feedback#14]
API allows only one cookie to be set in the response using the following code.

res.set('Set-Cookie', 'TRACK=true; Path=/');

Any attempt to create another cookie using this mechanism overwrites the previous cookie.

**Comment by nhoughto** [comment]
Hey

So res.set() just sets a given header with 'Set-Cookie' as the key, this is desirable behaviour for other HTTP headers where you want to be able to set and then update, or override a given header.

If you want to set one or more cookies, you can use res.cookie(name, value) which adds a cookie to the response rather than sets a header, so it can be called multiple times.

**Comment by ghsbhatia** [comment]
Thanks for your reply. I did not see it in sandbox definition API. 

How to set cookie attributes like secure and httpOnly?
