### ISSUE TITLE
Unable to add route with URL parameters and a space in the URL

### ISSUE THREAD

**Issue by tanushree-d2l** [getsandbox/feedback#25]
Hi Sandbox team,

I'm using the getsandbox.com site to define routes in order to create mock responses for an API. 

I'm running into an issue where if the route contains a space in it and requires one or more parameters, getsandbox is unable to hit the route: 
![sample](https://user-images.githubusercontent.com/71900131/94967910-0050c700-04ce-11eb-8276-68381572e8fa.PNG)

 I get the following error: ![error](https://user-images.githubusercontent.com/71900131/94967853-e2836200-04cd-11eb-8dec-41c166782d04.PNG)

Is there a syntactic workaround for this?

**Comment by nhoughto** [comment]
Haven't seen that use-case before, since space is an unsafe url character so its not recommended to use in the URL.. likely for this sort of reason.

The most obvious way would be to do `+` encoding of spaces, and add the `+` to the route definition, so `Sandbox.define('/test+this/{param}..` but browsers would generally encode a space to `%20` not `+`

We could look at supporting it better, but seems like a pretty niche edgecase

**Comment by tanushree-d2l** [comment]
I noticed that getsandbox accepts a single space character without the parameter, seems that its the combination of the two that are causing the error. 

My organization's use of getsandbox is dependent on this. Is this use-case something that you would be open to adding support for?

**Comment by nhoughto** [comment]
Ok so you definitely can't send an actual ` ` in the path, an un-encoded space that is, that will be rejected as an illegal char in a bunch of different places including GCP GLB.. so it will have to be encoded as + or %20, which is the default that browsers will do.

To support that in the definition is a little tricky but you can do it with a wildcard/regex match pretty easily:
```
Sandbox.define('/path/{catchall:.*}', 'get', function(req, res) {
    if (req.params.catchall == "space test") {
        res.send("matched space!")
    } else {
        res.send("missed - " + req.params.catchall);    
    }
});
```
